[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc -p tsconfig.json --noEmitOnError false || true",
]

[start]
cmd = "node dist/app.js"
